
package com.mycompany.poo.Interfases;
// paquetes del sistema
import com.mycompany.poo.Clases.Parqueo;

public class InterfaceParqueo extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfaceParqueo
     */
    private Parqueo Parqueo = new Parqueo(0, "UMG San Jose Pinula", 0);
    
    public InterfaceParqueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iuBtnMeterCarro = new javax.swing.JButton();
        uiBtnIngresarCapacidad = new javax.swing.JButton();
        uiBtnSacarCarro = new javax.swing.JButton();
        TextCapacidad = new javax.swing.JTextField();
        LbMensaje = new javax.swing.JLabel();
        LbnumParDispo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LbParqueoDisponible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parqueo UMG");

        iuBtnMeterCarro.setText("Meter Carro");
        iuBtnMeterCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iuBtnMeterCarroActionPerformed(evt);
            }
        });

        uiBtnIngresarCapacidad.setText("Ingresar Capacidad");
        uiBtnIngresarCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBtnIngresarCapacidadActionPerformed(evt);
            }
        });

        uiBtnSacarCarro.setText("Sacar Carro");
        uiBtnSacarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBtnSacarCarroActionPerformed(evt);
            }
        });

        TextCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCapacidadActionPerformed(evt);
            }
        });

        LbMensaje.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        LbMensaje.setText("lbDisponibles");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Parqueos Disponibles");

        LbParqueoDisponible.setFont(new java.awt.Font("HP Simplified Hans", 0, 36)); // NOI18N
        LbParqueoDisponible.setForeground(new java.awt.Color(51, 0, 255));
        LbParqueoDisponible.setText("0");
        LbParqueoDisponible.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbnumParDispo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uiBtnIngresarCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TextCapacidad)
                .addGap(447, 447, 447))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(iuBtnMeterCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(uiBtnSacarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LbParqueoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LbnumParDispo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiBtnIngresarCapacidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbParqueoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uiBtnSacarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(iuBtnMeterCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39)
                .addComponent(LbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iuBtnMeterCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iuBtnMeterCarroActionPerformed
        // TODO add your handling code here:
        String MeterCarro = this.Parqueo.MeterCarro();
        this.LbMensaje.setText(MeterCarro);
        this.LbParqueoDisponible.setText(String.valueOf(this.Parqueo.getParqueosDisponibles()));
        
    }//GEN-LAST:event_iuBtnMeterCarroActionPerformed

    private void uiBtnSacarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBtnSacarCarroActionPerformed
        // TODO add your handling code here:
        String SacarCarro =  this.Parqueo.sacarCarro();
        this.LbMensaje.setText(SacarCarro);
        this.LbParqueoDisponible.setText(String.valueOf(this.Parqueo.getParqueosDisponibles()));
        
    }//GEN-LAST:event_uiBtnSacarCarroActionPerformed
    
    // INGRESO DE LA CAPACIDAD DEL PARQUEO
    private void uiBtnIngresarCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBtnIngresarCapacidadActionPerformed
        // para programar el evento de dar clik
        int Capacidad = Integer.parseInt(this.TextCapacidad.getText());
        this.Parqueo.setNumeroParqueo(Capacidad);
       this.Parqueo.setParqueosDisponibles(Capacidad);
        this.LbParqueoDisponible.setText(String.valueOf(this.Parqueo.getParqueosDisponibles()));
    }//GEN-LAST:event_uiBtnIngresarCapacidadActionPerformed

    private void TextCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCapacidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceParqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbMensaje;
    private javax.swing.JLabel LbParqueoDisponible;
    private javax.swing.JLabel LbnumParDispo;
    private javax.swing.JTextField TextCapacidad;
    private javax.swing.JButton iuBtnMeterCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton uiBtnIngresarCapacidad;
    private javax.swing.JButton uiBtnSacarCarro;
    // End of variables declaration//GEN-END:variables
}
